//tengo que acordarme del espacio abajo del content-type
POST http://localhost:5000/users/
Content-Type: application/json

{
    "username":"Barbara",
    "password":"barbara.4",
    "email":"barbara@gmail.com",
    "role": "subscriber"
}
