//tengo que acordarme del espacio abajo del content-type
POST http://localhost:5000/users
Content-Type: application/json

{
    "usename": "Javi",
    "password": "javi",
    "email": "javi@gmail.com",
    "creationdate" : ""
}
