//tengo que acordarme del espacio abajo del content-type
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content" : "Este post estara en true",
    "important" : false
}

###
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{

}

//aqui puedo documentar la API