POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDQzODZiODc3MDBjOWNmODExZTA3NiIsInVzZXJuYW1lIjoiYmhqZGgiLCJpYXQiOjE2NTg1MDgzMTJ9.zF2riarR0ywOQ8Czp5u4KqJhktAPfkJqb4ivJekn6U0

{
    "title": "Hola",
    "adresse": "Me llamo barbara",
    "eventDate" : {
        "dateStart": "2002-03-03",
        "dateEnd": "2002-03-03"
    }
}
###
// test para saber que pasa si el body esta vacio
POST http://localhost:5000/posts
Content-Type: application/json

{
    "iduser":"62aa28388c63e0799c6eae1b", 
}
