POST http://localhost:5000/posts
Content-Type: application/json

{
    "iduser":"62aa28388c63e0799c6eae1b", 
    "title": "Hola",
    "description": "Me llamo barbara"
}

###
// test para saber que pasa si el body esta vacio
POST http://localhost:5000/posts
Content-Type: application/json

{
    "iduser":"62aa28388c63e0799c6eae1b", 
}
